version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: |
          wget https://download.checkmarx.com/9.3.0GA/Plugins/CxConsolePlugin-1.1.5.zip
          mkdir CxConsolePlugin
          unzip CxConsolePlugin-1.1.5.zip -d CxConsolePlugin
          cd CxConsolePlugin
          chmod +x runCxConsole.sh
          ./runCxConsole.sh Scan -CxServer "https://sulamerica.checkmarx.net" -TrustedCertificates enable -CxToken $token -LocationPath "folder" -OsaPathExclude CxConsolePlugin -Projectname "/CxServer/Teste"  
workflows:
  sample: 
    jobs:
      - build-and-test