version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: |
          wget https://download.checkmarx.com/9.3.0GA/Plugins/CxConsolePlugin-1.1.5.zip
          mkdir CxConsolePlugin
          unzip CxConsolePlugin-1.1.5.zip -d CxConsolePlugin
          cd CxConsolePlugin
          chmod +x runCxConsole.sh
          ./runCxConsole.sh Scan -CxServer "https://cxprivatecloud.checkmarx.net/" -TrustedCertificates -CxUser cassio -CxPassword Putaria@67 -LocationType "folder" -Projectname "/CxServer/SP/EMEA/LATAM/nova-8.com - 55/Damm Vulnerable dotNet Web Application" -LocationPath "${CIRCLE_WORKING_DIRECTORY}"  -Comment "Build Id : $CI_PIPELINE_ID" -Preset "Checkmarx Default" -ForceScan
workflows:
  sample: 
    jobs:
      - build-and-test